#! /usr/bin/env bash

PROFILE=$1

gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/foreground_color --type string "#00FF00"
gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/background_color --type string "#000000"
gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/bold_color --type string "#00FF00"
gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/palette --type string "#000000:#990000:#00A600:#999900:#0000B2:#B200B2:#00A6B2:#BFBFBF:#666666:#E50000:#00D900:#E5E500:#0000FF:#E500E5:#00E5E5:#E5E5E5"
