#! /bin/bash

PROFILE=$1

gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/foreground_color --type string "#FFFFFF"
gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/background_color --type string "#323232"
gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/bold_color --type string "#FFFFA9"
gconftool-2 --set /apps/gnome-terminal/profiles/$PROFILE/palette --type string "#323232:#D25252:#7FE173:#FFC66D:#4098FF:#F57FFF:#BED6FF:#EEEEEC:#535353:#F07070:#9DFF90:#FFE48B:#5EB7F7:#FF9DFF:#DCF4FF:#FFFFFF"
